---
deployment:
  tasks:
    - export DEPLOYPATH=/home/andre065/public_html/
    - /bin/cp -R public/* $DEPLOYPATH
    
    # - export DEPLOYPATH=/home/andre065/landingpage.andrewmasonmedia.com/
    # - /bin/cp -R public/* $DEPLOYPATH